apiVersion: v1
kind: Namespace
metadata:
  name: echo-server-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: echo-server-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      lables:
        app: echo-server
    spec:
      containers:
        - name: echo-server-container
          image: paulplintus/homelab:echo_server_v1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-svc
  namespace: echo-server-ns
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-server-ingress
  namespace: echo-server-ns
spec:
  ingressClassName: nginx
  rules:
    - host: echo-server.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-server-svc
                port:
                  number: 80
